name: "Counter-Strike: Source Dedicated Server (SteamCMD)"
slug: "css_steamcmd_server"
description: "Counter-Strike: Source Dedicated Server via SteamCMD (Linux) for Home Assistant OS"
version: "1.0.8"

arch:
  - amd64

startup: "application"
boot: "auto"
init: false

ports:
  27015/udp: 27015
  27015/tcp: 27015
  27020/udp: 27020

map:
  - share:rw
  - addon_config:rw

options:
  update_on_boot: true
  skip_steam_verify: false

  enable_debug: false

  hostname: "Home Assistant CS:S Server"
  maxplayers: 16
  map: "de_dust2"
  tickrate: 66

  gslt: ""

  write_cfg_files: true
  sv_lan: 1
  rcon_password: "CHANGE_ME"
  sv_password: ""

  log_on: true
  log_verbose: 0
  logaddress: ""

  enable_sourcetv: false
  sourcetv_name: "HAOS SourceTV"

schema:
  update_on_boot: bool
  skip_steam_verify: bool

  enable_debug: bool

  hostname: str
  maxplayers: int
  map: str
  tickrate: int
  gslt: str?

  write_cfg_files: bool
  sv_lan: int
  rcon_password: str
  sv_password: str?

  log_on: bool
  log_verbose: int
  logaddress: str?

  enable_sourcetv: bool
  sourcetv_name: str?
